### tampilkan semua resep

GET http://localhost:5000/resep

### get by name
GET http://localhost:5000/resep/name

###
POST http://localhost:5000/resep
Content-Type: application/json

{
    "judul" : "",
    "foto" : ".jpg",
    "bahan" : [],
    "proses" : []
}

### 
PUT http://localhost:5000/resep/id
Content-Type: application/json

{
    "judul" : "",
    "foto" : ".jpg",
    "bahan" : [],
    "proses" : []
}

### 
DELETE http://localhost:5000/resep/id

### login

POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}