### tampilkan semua resep

GET http://localhost:5000/resep

### get by name
GET http://localhost:5000/resep/search/name

### get by id
GET http://localhost:5000/resep/id


###
POST http://localhost:5000/resep
Content-Type: application/json

{
    "judul" : "ikan goreng",
    "foto" : "ikan-goreng.jpg",
    "bahan" : ["ikan"],
    "proses" : ["digoreng"]
}

### 
PUT http://localhost:5000/resep/64916bba1910396e945e64fd
Content-Type: application/json

{
    "judul" : "ikan goreng enak",
    "foto" : "ikan-goreng.jpg",
    "bahan" : ["ikan"],
    "proses" : ["digoreng"]
}

### 
DELETE http://localhost:5000/resep/id

### login

POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}